openapi: 3.0.3
info:
  title: Ledger Updates REST API
  description: This document specifies the REST API for Chronicle software.
  contact:
    email: contact@iota.org
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0
externalDocs:
  description: Find out more about IOTA
  url: "https://iota.org"
servers:
  - url: "http://127.0.0.1:8000"
tags:
  - name: historical
    description: Everything about the historical data.
  - name: ledger
    description: Everything about the ledger.
paths:
  /api/v1/gaps:
    get:
      tags:
        - historical
      summary: Returns general information about the historical data.
      description: Returns general information about the historical data.
      responses:
        "200":
          description: "Successful operation."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GapsResponse"
              examples:
                default:
                  $ref: "#/components/examples/get-gaps-response-example"
        "403":
          description: "Unsuccessful operation: indicates that the endpoint is not available for public use."
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml#/components/schemas/ForbiddenResponse"
        "500":
          description: "Unsuccessful operation: indicates that an unexpected, internal server error happened which prevented the node from fulfilling the request."
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml#/components/schemas/InternalErrorResponse"
  "/api/v1/ledger/updates/{address}":
    get:
      tags:
        - ledger
      summary: Get all ledger updates involving given a bech32 address.
      description: >-
        Get all ledger updates involving a given bech32 address.
      parameters:
        - in: path
          name: address
          schema:
            type: string
          example: iota1qpf0mlq8yxpx2nck8a0slxnzr4ef2ek8f5gqxlzd0wasgp73utryj430ldu
          required: true
          description: bech32 address that is referenced by the outputs.
        - in: query
          name: pageSize
          schema:
            type: number
          example: 1000
          description: Requested page size.
        - in: query
          name: sort
          schema:
            type: string
          example: "asc"
          description: "Describes the sort order for the milestone index of the updates. Possible values: asc, desc"
        - in: query
          name: startMilestoneIndex
          schema:
            type: number
          example: 1643383242
          description: Start the search from the given milestone index. Will be overridden by the pagingState if it is provided.
        - in: query
          name: cursor
          schema:
            type: string
          example: 1643383242.fa0de75d225cca2799395e5fc340702fc7eac821d2bdd79911126f131ae097a20100.100
          description: Starts the search from the cursor (milestoneIndex.outputId.pageSize)
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LedgerUpdateResponse"
              # examples:
              #   default:
              #     $ref: "#/components/examples/get-transactions-response-example"
        "400":
          description: "Unsuccessful operation: indicates that the provided address is invalid."
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml#/components/schemas/BadRequestResponse"
        "404":
          description: >-
            Unsuccessful operation: indicates that the requested data was not found.
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml#/components/schemas/NotFoundResponse"
        "500":
          description: >-
            Unsuccessful operation: indicates that an unexpected, internal
            server error happened which prevented the node from fulfilling the
            request.
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/iotaledger/tips/stardust-api/tips/TIP-0025/core-rest-api.yaml#/components/schemas/InternalErrorResponse"
components:
  schemas:
    Gap:
      description: >-
        Describes a gap in the historical data. A gap is defined as the range milestone indices [from, to). Note that to is exclusive.
      properties:
        start:
          type: number
          description: The first milestone index for which the node does not have data.
        end:
          type: number
          description: The first milestone index for which the node has data again.
    GapsResponse:
      description: Returns information about missing data.
      properties:
        gaps:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/Gap"
          description: The name of the node.
    LedgerUpdate:
      description: Information about ledger updates.
      properties:
        milestoneIndex:
          type: integer
          description: The index of the timestamp.
        milestoneTimestamp:
          type: integer
          description: The timestamp at which the milestone was issued.
        outputId:
          type: string
          description: The output ID (transaction hash + output index) of the update. Hex-encoded with 0x prefix.
        isSpent:
          type: boolean
          description: Indicates if the output was spent or not.
      required:
        - milestoneIndex
        - milestoneTimestamp
        - outputId
        - isSpent
    LedgerUpdateResponse:
      description: A list of ledger updates associated with an address.
      properties:
        items:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/LedgerUpdate"
          description: A list of ledger updates.
        cursor:
          type: string
          description: The cursor to use for getting the next page of results.
          nullable: true
      required:
        - updates
  examples:
    get-gaps-response-example:
      value:
        - from: 15465
          end: 15482
        - from: 15487
          end: 15499
    # get-transactions-response-example:
    #   value:
    #     - "0x0c78e998f5177834ecb3bae1596d5056af76e487386eecb19727465b4be86a79"
    #     - "0x309b169bfa60c8cf80afd730741862d200405d5df7cabfe9b564361dce1f7036"
    #     - "0xc138ecdc882010245e9574fbc1f1f43cc7c182fa890e46e018365dd49de0f16e"
